source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'NAConfettiView_Example' do
  pod "NAConfettiView", :path => "../"
end

target 'NAConfettiView_Tests' do
  pod "NAConfettiView", :path => "../"

  
end
